// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package grpcServer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReceiveLogsClient is the grpcClient API for ReceiveLogs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReceiveLogsClient interface {
	Receive(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Response, error)
}

type receiveLogsClient struct {
	cc grpc.ClientConnInterface
}

func NewReceiveLogsClient(cc grpc.ClientConnInterface) ReceiveLogsClient {
	return &receiveLogsClient{cc}
}

func (c *receiveLogsClient) Receive(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/grpcServer.ReceiveLogs/Receive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReceiveLogsServer is the grpcServer API for ReceiveLogs service.
// All implementations must embed UnimplementedReceiveLogsServer
// for forward compatibility
type ReceiveLogsServer interface {
	Receive(context.Context, *LogRequest) (*Response, error)
	mustEmbedUnimplementedReceiveLogsServer()
}

// UnimplementedReceiveLogsServer must be embedded to have forward compatible implementations.
type UnimplementedReceiveLogsServer struct {
}

func (UnimplementedReceiveLogsServer) Receive(context.Context, *LogRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Receive not implemented")
}
func (UnimplementedReceiveLogsServer) mustEmbedUnimplementedReceiveLogsServer() {}

// UnsafeReceiveLogsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReceiveLogsServer will
// result in compilation errors.
type UnsafeReceiveLogsServer interface {
	mustEmbedUnimplementedReceiveLogsServer()
}

func RegisterReceiveLogsServer(s grpc.ServiceRegistrar, srv ReceiveLogsServer) {
	s.RegisterService(&ReceiveLogs_ServiceDesc, srv)
}

func _ReceiveLogs_Receive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReceiveLogsServer).Receive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/grpcServer.ReceiveLogs/Receive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReceiveLogsServer).Receive(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReceiveLogs_ServiceDesc is the grpc.ServiceDesc for ReceiveLogs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReceiveLogs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpcServer.ReceiveLogs",
	HandlerType: (*ReceiveLogsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Receive",
			Handler:    _ReceiveLogs_Receive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpcServer.proto",
}
